In [2]:
#-*- coding:utf-8 -*-
from sklearn import datasets
from sklearn import linear_model
from sklearn.model_selection import train_test_split
from sklearn import metrics
import os
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
%matplotlib inline

In [3]:
from sklearn.svm import LinearSVC
from sklearn.datasets import make_classification

In [4]:
#生产数据
X,y = make_classification(n_features=4,random_state=0)
print(X,y)

[[-7.15602562e-02  2.29553900e-01  2.16543447e-01  6.52739792e-02]
 [-4.03257104e-01  2.00618406e+00  2.02751248e+00  8.50891944e-01]
 [-1.13058206e+00 -2.02959251e-02 -7.10233633e-01 -1.44099108e+00]
 [ 1.83324682e-01 -7.74610354e-01 -7.66054695e-01 -2.93668633e-01]
 [-2.86920000e-01 -7.16952984e-01 -9.86585088e-01 -8.48214735e-01]
 [-2.56042975e+00  4.02232337e-01 -1.10074198e+00 -2.95958826e+00]
 [ 4.22341441e-01 -2.03911440e+00 -2.05321581e+00 -8.49123046e-01]
 [-5.09792713e-01  4.92658944e-01  2.48206729e-01 -3.09590732e-01]
 [ 7.21669496e-01 -1.12155664e+00 -8.31839865e-01  1.50742097e-01]
 [-9.86132567e-01  1.71053103e+00  1.33828180e+00 -8.53410903e-02]
 [-7.23168038e-02 -7.73668334e-01 -9.20383253e-01 -6.15748704e-01]
 [ 4.55946498e-01 -4.57868762e-01 -2.41527100e-01  2.65199620e-01]
 [ 3.93906076e-01  3.90247346e-01  6.81520677e-01  7.61804328e-01]
 [ 2.03196825e+00  8.40398655e-01  2.18718140e+00  3.13482383e+00]
 [ 4.58931008e-02 -2.61403392e-01 -2.68225264e-01 -1.19266118e

In [5]:
#调用svm classification API
clf = LinearSVC(random_state=0, tol=1e-5)

In [6]:
clf.fit(X, y)

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=0, tol=1e-05, verbose=0)

In [8]:
#模型精度
presion = clf.score(X, y)

0.93

In [10]:
clf.decision_function


<bound method LinearClassifierMixin.decision_function of LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=0, tol=1e-05, verbose=0)>

In [11]:
print(clf.coef_)

[[0.08551853 0.39414771 0.49848086 0.37514369]]


In [12]:
print(clf.intercept_)

[0.28417571]


In [13]:
print(clf.predict([[0, 0, 0, 0]]))

[1]
